name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build-params: ${{ steps.build-params.outputs.build-params }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - id: build-params
        uses: yuya-takeyama/mobb/actions/generate-build-params@initial
        with:
          root-dir: apps
          global-config-file: apps/mobb-global.yaml
          datetime-tag-timezone: Asia/Tokyo

  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        build-params: ${{ needs.setup.outputs.build-params }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ toJSON(matrix.build-params) }}"
