name: build-docker

on:
  push:
    branches:
      - main
    paths:
      - apps
  pull_request:
    paths:
      - apps

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      build-params: ${{ steps.build-params.outputs.build-params }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - id: build-params
        uses: yuya-takeyama/mobb/actions/generate-build-docker-params@7b5d44127906c9a83546ae3911ef1c32ffae3d4b # v0.1.0-1
        with:
          root-dir: apps
          global-config-file: apps/mobb-global.yaml
          datetime-tag-timezone: Asia/Tokyo

  build:
    name: ${{ matrix.build-params.label }}
    needs: setup
    if: ${{ needs.setup.outputs.build-params != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        build-params: ${{ fromJSON(needs.setup.outputs.build-params) }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: |
          echo "$BUILD_PARAMS"
        env:
          BUILD_PARAMS: ${{ toJSON(matrix.build-params) }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ matrix.build-params.value.docker.aws.identity.iam-role }}
          aws-region: ${{ matrix.build-params.value.docker.aws.identity.region }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: ${{ matrix.build-params.value.docker.aws.registry.type }}
      - uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          context: ${{ matrix.build-params.value.docker.context }}
          push: true
          tags: ${{ matrix.build-params.value.docker.tags }}
          platforms: ${{ matrix.build-params.value.docker.platforms }}
